#ifndef CONTROLCHANNELPRIVILEGE_H
#define CONTROLCHANNELPRIVILEGE_H

enum ControlChannelPrivilege {
    MONITOR,
    CTRL_ACCESS_SWITCH_OVER,
    CTRL_ACCESS,
    EXCLUSIVE
};

#endif // CONTROLCHANNELPRIVILEGE_H
