#ifndef OPENGV_GLOBAL_H
#define OPENGV_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENGV_LIBRARY)
#  define OPENGVSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENGVSHARED_EXPORT Q_DECL_IMPORT
#endif

#define CONTROL_CHANNEL_DEF_PORT 3956

#define SPEC_VERSION_MINOR 2
#define SPEC_VERSION_MAJOR 2

//#define ENABLE_LOG4CPP 1

#endif // OPENGV_GLOBAL_H
